name: Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Build docker containers
        run: docker-compose build --build-arg "redis_version=7.0.7" redis-cluster
      - name: Initiate docker containers
        run: docker-compose -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check docker logs
        run: sleep 20 && docker logs redis && docker logs redis_cluster
      - name: Setup NodeJS v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run lint
      - run: DEBUG="ioredis:*" yarn run test:e2e
